//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puzzle_editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puzzle_editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barrier {
            get {
                object obj = ResourceManager.GetObject("barrier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cube {
            get {
                object obj = ResourceManager.GetObject("cube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door {
            get {
                object obj = ResourceManager.GetObject("door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT 
        ///    w.ElementId AS `WallId`, c.ElementId AS `CubeId`, k.ElementId AS `KeyId`, k.Color AS `KeyColor`,
        ///    d.ElementId AS `DoorId`, d.Color AS `DoorColor`, b.ElementId AS `ButtonId`, b.Color AS `ButtonColor`,
        ///    r.ElementId AS `BarrierId`, r.Color AS `BarrierColor`, e.ElementId AS `LazerEmitterId`, e.Direction AS `LazerDirection`,
        ///    e.Energy AS `LazerEnergy`, m.ElementId AS `MedicineChestId`, m.Size AS `MedicineSize`
        ///FROM `model`.`gameelement` A
        ///        LEFT JOIN `model`.`wall` w ON A.id = w. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetElement {
            get {
                return ResourceManager.GetString("GetElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT 
        ///    X, Y, w.ElementId AS `WallId`, c.ElementId AS `CubeId`, k.ElementId AS `KeyId`, k.Color AS `KeyColor`,
        ///    d.ElementId AS `DoorId`, d.Color AS `DoorColor`, b.ElementId AS `ButtonId`, b.Color AS `ButtonColor`,
        ///    r.ElementId AS `BarrierId`, r.Color AS `BarrierColor`, e.ElementId AS `LazerEmitterId`, e.Direction AS `LazerDirection`,
        ///    e.Energy AS `LazerEnergy`, m.ElementId AS `MedicineChestId`, m.Size AS `MedicineSize`
        ///FROM `model`.`gameelement` A
        ///        LEFT JOIN `model`.`wall` w ON A.id = w. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetElements {
            get {
                return ResourceManager.GetString("GetElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT PlayerX, PlayerY, ExitX, ExitY FROM `model`.`location`;.
        /// </summary>
        internal static string GetLocationIO {
            get {
                return ResourceManager.GetString("GetLocationIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT COUNT(*) FROM `model`.`gameelement` JOIN `model`.`wall` ON `model`.`gameelement`.`id` = `model`.`wall`.`ElementId` GROUP BY LocationId;.
        /// </summary>
        internal static string GetWallsCount {
            get {
                return ResourceManager.GetString("GetWallsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lazeremitter {
            get {
                object obj = ResourceManager.GetObject("lazeremitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicinechest {
            get {
                object obj = ResourceManager.GetObject("medicinechest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player {
            get {
                object obj = ResourceManager.GetObject("player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE `model`.`location` SET `Name` = @name, `TextureType` = @textureType, `Width` = @width, `Height` = @height, `PlayerX` = @playerX, `PlayerY` = @playerY, `ExitX` = @exitX, `ExitY` = @exitY, `InventoryCapacity` = @capacity WHERE (`Number` = @locationNumber).
        /// </summary>
        internal static string SetLocationParameters {
            get {
                return ResourceManager.GetString("SetLocationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на abc8734.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
